//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Automation_MessagesMetadata))]
    public partial class Automation_Messages
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string ForwardLink { get; set; }
        public Nullable<System.Guid> UnreadBy { get; set; }
        public Nullable<System.Guid> ReadBy { get; set; }
        public Nullable<System.Guid> genericId { get; set; }
    
        public virtual Automation_Generic Automation_Generic { get; set; }
    }
}
