//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Automation_TasksMetadata))]
    public partial class Automation_Tasks
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> Responsible { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string Description { get; set; }
        public string Filter1 { get; set; }
        public string Filter2 { get; set; }
        public string Filter3 { get; set; }
        public string ApproveHtml { get; set; }
        public string ApproveScript { get; set; }
        public string RejectHtml { get; set; }
        public string RejectScript { get; set; }
        public string Script { get; set; }
        public string Html { get; set; }
        public Nullable<int> TaskOrder { get; set; }
        public Nullable<System.Guid> genericId { get; set; }
    
        public virtual Automation_Generic Automation_Generic { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
