//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(BaniChav_TotalMetadata))]
    public partial class BaniChav_Total
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaniChav_Total()
        {
            this.BaniChav_ReturnedProducts = new HashSet<BaniChav_ReturnedProducts>();
        }
    
        public System.Guid ID { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string TeamOfSale { get; set; }
        public Nullable<System.Guid> DelivererID { get; set; }
        public string DelivererCode { get; set; }
        public Nullable<System.Guid> SuperVisorOfSupplyID { get; set; }
        public string SuperVisorOfSupplyCode { get; set; }
        public Nullable<System.Guid> SuperVisorOfSaleID { get; set; }
        public string SuperVisorOfSaleCode { get; set; }
        public Nullable<System.Guid> VisitorID { get; set; }
        public string VisitorCode { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual USERS USERS { get; set; }
        public virtual USERS USERS1 { get; set; }
        public virtual USERS USERS2 { get; set; }
        public virtual USERS USERS3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaniChav_ReturnedProducts> BaniChav_ReturnedProducts { get; set; }
    }
}
