//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(ForumGroupsMetadata))]
    public partial class ForumGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForumGroups()
        {
            this.ForumComments = new HashSet<ForumComments>();
            this.ForumPosts = new HashSet<ForumPosts>();
        }
    
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> AdminUserId { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumComments> ForumComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumPosts> ForumPosts { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
