//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(ForumCommentsMetadata))]
    public partial class ForumComments
    {
        public System.Guid ID { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public System.Guid ForumPostID { get; set; }
        public System.Guid ForumGroupID { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
    
        public virtual ForumGroups ForumGroups { get; set; }
        public virtual ForumPosts ForumPosts { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
