//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(GalleryMetadata))]
    public partial class Gallery
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Alt { get; set; }
        public byte[] FileData { get; set; }
        public Nullable<bool> IsUsedInSlider { get; set; }
    }
}
