//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(LNK_User_VideoMetadata))]
    public partial class LNK_User_Video
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public int VideoID { get; set; }
    
        public virtual Videos Videos { get; set; }
    }
}
