//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDBEntities : DbContext
    {
        public MainDBEntities()
            : base("name=MainDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Favorites> Favorites { get; set; }
        public virtual DbSet<Features> Features { get; set; }
        public virtual DbSet<Gallery> Gallery { get; set; }
        public virtual DbSet<LNK_User_Video> LNK_User_Video { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<News_Comments> News_Comments { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<PARAMETERS> PARAMETERS { get; set; }
        public virtual DbSet<PERMISSIONS> PERMISSIONS { get; set; }
        public virtual DbSet<Product_Gallery> Product_Gallery { get; set; }
        public virtual DbSet<Product_Groups> Product_Groups { get; set; }
        public virtual DbSet<Product_Tags> Product_Tags { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<REPORTS> REPORTS { get; set; }
        public virtual DbSet<Videos> Videos { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
        public virtual DbSet<WareHouse_Types> WareHouse_Types { get; set; }
        public virtual DbSet<Product_Features> Product_Features { get; set; }
        public virtual DbSet<Product_Comments> Product_Comments { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ForumComments> ForumComments { get; set; }
        public virtual DbSet<ForumGroups> ForumGroups { get; set; }
        public virtual DbSet<ForumPosts> ForumPosts { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<BaniChav_Total> BaniChav_Total { get; set; }
        public virtual DbSet<Automation_Generic> Automation_Generic { get; set; }
        public virtual DbSet<Automation_Tasks> Automation_Tasks { get; set; }
        public virtual DbSet<BaniChav_ReturnedProducts> BaniChav_ReturnedProducts { get; set; }
        public virtual DbSet<Automation_Messages> Automation_Messages { get; set; }
    }
}
