//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Product_GalleryMetadata))]
    public partial class Product_Gallery
    {
        public System.Guid GalleryID { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
