//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(Product_FeaturesMetadata))]
    public partial class Product_Features
    {
        public int PF_ID { get; set; }
        public string Value { get; set; }
        public Nullable<int> Price { get; set; }
        public System.Guid ProductID { get; set; }
        public System.Guid FeatureID { get; set; }
    
        public virtual Features Features { get; set; }
        public virtual Products Products { get; set; }
    }
}
