//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(REPORTSMetadata))]
    public partial class REPORTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORTS()
        {
            this.PARAMETERS = new HashSet<PARAMETERS>();
            this.ROLES = new HashSet<ROLES>();
        }
    
        public int Report_Id { get; set; }
        public System.DateTime LastModified { get; set; }
        public bool Inactive { get; set; }
        public string ReportName { get; set; }
        public string ReportDescription { get; set; }
        public string Template { get; set; }
        public string StoredProcedureName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAMETERS> PARAMETERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLES> ROLES { get; set; }
    }
}
