//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(USERSMetadata))]
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.ForumComments = new HashSet<ForumComments>();
            this.ForumGroups = new HashSet<ForumGroups>();
            this.ForumPosts = new HashSet<ForumPosts>();
            this.Orders = new HashSet<Orders>();
            this.ROLES = new HashSet<ROLES>();
            this.BaniChav_Total = new HashSet<BaniChav_Total>();
            this.BaniChav_Total1 = new HashSet<BaniChav_Total>();
            this.BaniChav_Total2 = new HashSet<BaniChav_Total>();
            this.BaniChav_Total3 = new HashSet<BaniChav_Total>();
            this.Automation_Tasks = new HashSet<Automation_Tasks>();
        }
    
        public System.Guid User_Id { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Title { get; set; }
        public string Initial { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public string ActiveCode { get; set; }
        public string Pic { get; set; }
        public string FLName { get; set; }
        public string LFName { get; set; }
        public string Post { get; set; }
        public string Department { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumComments> ForumComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumGroups> ForumGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForumPosts> ForumPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLES> ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaniChav_Total> BaniChav_Total { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaniChav_Total> BaniChav_Total1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaniChav_Total> BaniChav_Total2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaniChav_Total> BaniChav_Total3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Automation_Tasks> Automation_Tasks { get; set; }
    }
}
