//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernTricks.Models
{
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(WareHouseMetadata))]
    public partial class WareHouse
    {
        public int WareHouseID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public int Count { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual WareHouse_Types WareHouse_Types { get; set; }
    }
}
